### ISSUE TITLE
About AP Loss train time

### ISSUE THREAD

**Issue by cape-zck** [Xudangliatiger/APE-Loss#1]
Hello, thank you very much for your great work. Recently I am researching and learning APE-Loss. But when I run this project, I found that its training speed had become very slow, five or six times slower than the original baseline. Is this normal, or did I go wrong somewhere?
Looking forward to your reply, thank you

**Comment by Xudangliatiger** [comment]
The training speed of APE loss is slower than GL, GFL and VFL. If you want to accurate the training, you may downsize your batchsize, since the rank pairs are constructed from all samples in one batch (so the pair-wise ranking has O(n^2) time complexity, n is the number of samples in one batch).

**Comment by Xudangliatiger** [comment]
Or you can modify the codes so that the ranking pairs are only formed in every single image. Recently, we employ the single image ranking on DETR and it works very well.

**Comment by cape-zck** [comment]
Thank you for your advice, it is very helpful to me！
